# Generated by Django 5.1 on 2024-08-17 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Q1', 'High Impact / Low Effort'), ('Q2', 'High Impact / High Effort'), ('Q3', 'Low Impact / High Effort'), ('Q4', 'Low Impact / Low Effort')], editable=False, max_length=2, null=True),
        ),
    ]
